### PR TITLE
(MODULES-1780) Add gsub function

### PR DESCRIPTION
**Pull request by petems**
Was at a customer site, realised we didn't have gsub in stdlib! This cannot stand! :smile:

### CODE REVIEW

**Comment by elyscape** [comment]
This is built in to Puppet.  Example from [the function documentation for `regsubst()`](https://docs.puppetlabs.com/references/latest/function.html#regsubst):
```puppet
$x = regsubst($ipaddress, '([0-9]+)', '<\1>', 'G')
```

**Comment by petems** [comment]
@elyscape This could be used in Puppet < 4 though? :+1:

**Comment by elyscape** [comment]
@petems [It has been built-in since at least Puppet 2.7](https://docs.puppetlabs.com/references/2.7.latest/function.html#regsubst).

**Comment by elyscape** [comment]
In fact, [it has been built-in since Puppet 0.24.8](https://docs.puppetlabs.com/references/0.24.8/function.html#regsubst).  Pretty sure we don't need it here.

**Comment by petems** [comment]
@elyscape Welp, now I feel like an idiot! :smile:

**Comment by elyscape** [comment]
@petems As a side note, the README seems to contain:

1. Some of the output of an aborted `git merge` (i.e. `<<<<<<< HEAD`)
2. Reformatted and expanded documentation for some functions
3. Duplicate old documentation for those same functions

Just something to be aware of for your working tree.

**Comment by petems** [comment]
Yeah, my rebase went wrong, didnt bother fixing it once I realised Gsub wasnt needed :+1:

**Pull request closed without merging**
