### PR TITLE
(maint) Correct misspellings

### PR DESCRIPTION
**Pull request by ehom**

### CODE REVIEW

**Comment by peterhuene** [comment]
# [Codecov](https://codecov.io/gh/puppetlabs/puppetlabs-stdlib/pull/1081?src=pr&el=h1) Report
> Merging [#1081](https://codecov.io/gh/puppetlabs/puppetlabs-stdlib/pull/1081?src=pr&el=desc) into [master](https://codecov.io/gh/puppetlabs/puppetlabs-stdlib/commit/352ac11e7e30de4dd128bfc3f10b4d854e16df6b&el=desc) will **increase** coverage by `0.91%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/puppetlabs/puppetlabs-stdlib/pull/1081?src=pr&el=tree)

```diff
@@            Coverage Diff            @@
##           master   #1081      +/-   ##
=========================================
+ Coverage    4.54%   5.46%   +0.91%     
=========================================
  Files         183     183              
  Lines        5238    5238              
=========================================
+ Hits          238     286      +48     
+ Misses       5000    4952      -48     
```


| [Impacted Files](https://codecov.io/gh/puppetlabs/puppetlabs-stdlib/pull/1081?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [lib/puppet/type/file\_line.rb](https://codecov.io/gh/puppetlabs/puppetlabs-stdlib/pull/1081/diff?src=pr&el=tree#diff-bGliL3B1cHBldC90eXBlL2ZpbGVfbGluZS5yYg==) | `96.36% <0.00%> (+1.81%)` | :arrow_up: |
| [lib/puppet/provider/file\_line/ruby.rb](https://codecov.io/gh/puppetlabs/puppetlabs-stdlib/pull/1081/diff?src=pr&el=tree#diff-bGliL3B1cHBldC9wcm92aWRlci9maWxlX2xpbmUvcnVieS5yYg==) | `62.62% <0.00%> (+47.47%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/puppetlabs/puppetlabs-stdlib/pull/1081?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/puppetlabs/puppetlabs-stdlib/pull/1081?src=pr&el=footer). Last update [352ac11...7d9648b](https://codecov.io/gh/puppetlabs/puppetlabs-stdlib/pull/1081?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by peterhuene** [comment]
Where in the world did the CodeCov report come from? 😮 

Is this something I set up like 5 years ago and if so how did this suddenly trigger now?

**Comment by cmccrisken-puppet** [comment]
@peterhuene My guess is it was [this PR](https://github.com/puppetlabs/puppetlabs-stdlib/pull/1068) that enabled it on the PRs. It may have been there as a Rake task to run locally from when you originally added it 5 years ago, perhaps?

**Comment by peterhuene** [comment]
Bizarre.  Please let me know if I appear to comment (obviously it wasn't *me* commenting on it) on future PRs than the @codecov-io bot.

**Pull request merged**
