### PR TITLE
(MODULES-4908) adds support for sensitive data type to pw_hash

### PR DESCRIPTION
**Pull request by eputnam**
Also includes a small fix to integer_spec so tests pass.

### CODE REVIEW

**Comment by eputnam** [comment]
blocked by Appveyor running tests with Puppet 4.2.3

**Comment by eputnam** [comment]
no longer blocked and ready for merge

**Comment by mwhahaha** [comment]
This seems to have broken our tests runs under 4.5.3 http://logs.openstack.org/34/489534/5/check/gate-puppet-pacemaker-puppet-unit-4.5-centos-7/3ee7b4d/console.html#_2017-08-02_05_57_10_708889

**Comment by eputnam** [comment]
@mwhahaha makes sense, the Sensitive type wasn't introduced until Puppet 4.6.x

**Comment by mwhahaha** [comment]
Yea is problematic because we still run 4.5 for tests. We're pinning to 4.16.0 as a work around but just wanted to note this.

**Pull request merged**
