### PR TITLE
add Stdlib::Port, Stdlib::Privilegedport & Stdlib::Unprivilegedport

### PR DESCRIPTION
**Pull request by b4ldr**

### CODE REVIEW

**Comment by b4ldr** [comment]
might be better to have 

```puppet
Stdlib::Port
Stdlib::Port::Privlaged
Stdlib::Port::Unprivlaged
```

happy to change if thats prfered

**Comment by b4ldr** [comment]
rebased and updated to use new type testing as per #856

**Comment by pegasd** [comment]
I'd love to see some progress on this.
Is there a specific hold-up preventing something in here?

FWIW, I'd love to see the alternative naming version implemented. Namely, these would be great:

```
Stdlib::Port
Stdlib::Port::Privileged
Stdlib::Port::Unprivileged
```

**Comment by b4ldr** [comment]
I did a rebase to fix the README conflict and renamed the types as suggested.  `Stdlib::Port::Privileged` seems more inline with other types

**Pull request merged**
