### PR TITLE
Adding markdown for the range() function's 3rd argument

### PR DESCRIPTION
**Pull request by robruma**
This documents the feature added in #56

### CODE REVIEW

**Comment by igalic** [comment]
:+1:

**Comment by mhaskel** [comment]
Hi @robruma, thanks for the contribution! Could you rebase this against master so it only contains the one commit with your changes? Thanks!

**Comment by robruma** [comment]
@mhaskel Hopefully this is what you expected, please let me know if you'd rather me squash all the changes... Thanks

**Comment by mhaskel** [comment]
@robruma We'd like this to be a squashed down to a single commit before we merge it (and it shouldn't have all the merge commits it has now)

**Comment by robruma** [comment]
@mhaskel sorry for the delay, hopefully this commit is satisfactory. Thanks

**Comment by mhaskel** [comment]
Looks good, thanks @robruma !

**Pull request merged**
