### PR TITLE
fixed wrong comment in unixpath.pp

### PR DESCRIPTION
**Pull request by c33s**
https://tickets.puppetlabs.com/browse/MODULES-6221

### CODE REVIEW

**Comment by pegasd** [comment]
Should the `contain a "."` part be here?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by c33s** [comment]
oh this was a wrong assumption. i digged through an puppetlabs-lvm error to `stdlib::absolutepath` which is using `unixpath`. so a assumed it has to be a absolute unix path which also does not contain any relative parts (`/home/../etc`)

i remove the dots part from the PR

tested the regex with https://regex101.com/

is/should this be a valid unixpath?

```/./......../'''ääÄÄÄvffoo/ü/:\\-__##../bar/com```

**Comment by eputnam** [comment]
That _is_ a valid unix path, yes.

**Comment by tphoney** [comment]
Thanks @c33s  !

**Pull request merged**
