### PR TITLE
adds new parser called is_absolute_path

### PR DESCRIPTION
**Pull request by logicminds**
I really like the validate_absolute_path function and needed similar functionality to perform conditional logic on installer locations so I created the is_absolute_path function.

This uses the same code as the validate function but only accepts one argument and also returns a value.

### CODE REVIEW

**Comment by igalic** [comment]
@logicminds rather than duplicating the code, i'd now switch validate_absolute_path to calling this function.

**Comment by logicminds** [comment]
@igalic I gave that some serious thought but I just assumed the performance would be better without having to call a puppet function from within a puppet function multiple times.  This might be negligible if using once but it folks are using this 50 times across their entire catalog, a 100 ms delay adds up pretty quick.  I have no benchmarks to back up my claim though.

**Comment by igalic** [comment]
so, we have a [loop](https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/lib/puppet/parser/functions/validate_absolute_path.rb#L44-L67)

```ruby
candidates.each do |path|
  function_is_absolute_path([path]) or raise Puppet::ParseError, ("#{path.inspect} is not an absolute path.")
end
```

now, a compiler that cannot figure out that this is a hot-spot, and needs optimization probably isn't worth its money, even if it's free.

imo, it's probably cheaper to keep the code in one parser function, than wonder why down the road the two of them are behaving differently.

however: i'm not an stdlib maintainer, so lets wait what @puppetlabs has to say!

**Comment by logicminds** [comment]
Well that is definitely much cleaner.

**Comment by logicminds** [comment]
This PR is only adding a function while most of this conversation is about altering an existing function to rely on a yet to be included function. We need to have a new PR for altering the validation_absolute_path and keep discussing there instead of here.

**Comment by bmjen** [comment]
@logicminds I agree with @igalic. For maintainability purposes it would be best to use DRY principles.

Also, I'd be a proponent of coupling the refactoring of `validate_absolute_path` in this PR if you have the bandwidth to do it. This way the conversation can be cohesive in the why and the when.

**Comment by logicminds** [comment]
ok I'll refactor soon and rebase.

**Comment by logicminds** [comment]
@bmjen  this is ready to go.

**Comment by bmjen** [comment]
@logicminds Thanks!

**Pull request merged**
