### PR TITLE
Adding a respond_to function

### PR DESCRIPTION
**Pull request by danzilio**
This PR adds a `respond_to` function to check if a resource type has a particular parameter, similar (in concept) to the `respond_to?` method in Ruby. This could be useful in a number of circumstances, not sure if I'm the only one that finds this function interesting.

### CODE REVIEW

**Comment by elyscape** [comment]
> This could be useful in a number of circumstances

Could you provide some examples?  I'm not really sure I see the use case at present.

**Comment by danzilio** [comment]
Sure!! The most useful (not contrived) example I can think of is supporting different module interfaces. For example, the `camptocamp/archive`  and `nanliu/archive` modules all do basically the same thing, but have different interfaces. If I want to be able to support both modules, I need to adjust the parameters I'm calling based on the interface available to me.

To pull a file with `nanliu/archive` I would use:

```
archive { 'apache-tomcat-6.0.26':
  ensure        => present,
  source        => 'http://archive.apache.org/dist/tomcat/tomcat-6/v6.0.26/bin/apache-tomcat-6.0.26.tar.gz',
  extract_path  => '/opt',
}
```

But with `camptocamp/archive` I would use:

```
archive { 'apache-tomcat-6.0.26':
  ensure => present,
  url    => 'http://archive.apache.org/dist/tomcat/tomcat-6/v6.0.26/bin/apache-tomcat-6.0.26.tar.gz',
  target => '/opt',
}
```

To abstract this away and allow my module users to pick whichever `archive` module they wish, I need to check the 'signature' of the `archive` resource. Here's how I would implement that using this `respond_to` function:

```
class fetch (
  $filename = 'apache-tomcat-6.0.26',
  $url = 'http://archive.apache.org/dist/tomcat/tomcat-6/v6.0.26/bin/apache-tomcat-6.0.26.tar.gz',
  $target = '/opt',
) {

  if respond_to('archive', 'url') and respond_to('archive', 'target') {
    archive { $filename:
      ensure => present,
      url    => $url,
      target => $target,
    }
  } 
  elsif respond_to('archive', 'source') and respond_to('archive', 'extract_path') {
    archive { $filename:
      ensure        => present,
      source        => $url,
      extract_path  => $target,
    }
  }
  else {
    fail('No supported archive module installed. Please install camptocamp/archive or nanliu/archive.')
  }
}
```

I could be the only one who wants to do something like this (I could also be nuts to want to do this). I just thought I'd submit it and see what the discussion was. If there's interest, I'll write some tests and docs for this PR. Also, if there are better ways to implement this, I'd love to hear how!

**Comment by danzilio** [comment]
Based on some feedback, I just added the ability to pass an array of parameters. The example above would now look like this:

```
class fetch (
  $filename = 'apache-tomcat-6.0.26',
  $url = 'http://archive.apache.org/dist/tomcat/tomcat-6/v6.0.26/bin/apache-tomcat-6.0.26.tar.gz',
  $target = '/opt',
) {

  if respond_to('archive', ['url', 'target']) {
    archive { $filename:
      ensure => present,
      url    => $url,
      target => $target,
    }
  } 
  elsif respond_to('archive', ['source', 'extract_path']) {
    archive { $filename:
      ensure        => present,
      source        => $url,
      extract_path  => $target,
    }
  }
  else {
    fail('No supported archive module installed. Please install camptocamp/archive or nanliu/archive.')
  }
}
```

**Comment by purpleidea** [comment]
@danzilio Cool idea, but (and maybe I'm misunderstanding) but what if the other module implements the parameters that you're checking for in the first... There's no guarantee this won't break!

IOW, cool idea, but this might end up being more trouble than it's worth.
Now if modules were fully qualified, eg: danzilio::archive, then that would solve your problem I think.

Since that might not change, perhaps each module could support a modulename::namespace class value which would equal danzilio or whatever the module namespace uuid is... Then you could test based on that.

HTH

**Comment by danzilio** [comment]
That's a good point. This function ultimately requires some knowledge of the other classes/resources you're using. I think this would work great with some kind of soft dependency mechanism in the module metadata. @garethr talked about some kind of interface system in a talk a few years ago. The example from his slides:

```
interface packageandservice {
  $version
  $enable
  $package_name
  $template
}
```

With the invocation looking something like this:

```
class diamond (
  $version,
  $enable,
  $package_name,
  $template,
) {
  implements packageandservice
```

This kind of functionality would obviate the need for this function because I could (I assume) just check to see what interface the class is implementing. I'd love to see something like that.

**Comment by hlindberg** [comment]
While I think it is useful to have reflection on types (i.e. being able to get information about their structure, attributes, etc.) I do not think that using such mechanisms to achieve Duck Typing (Ruby style - checking one 'responds_to', or Go style - checking multiple parameters) is going to be very successful in terms of maintainability. 

I would want the check to be based on the type - either the implementation type, or an interface that an implementation type has declared that it implements. I can imagine a function `module_of(type)` that returns the module name of the type. Then the decision can be based on that. Unfortunately this requires using weak (i.e. unlisted) dependencies since module meta data cannot describe "requires one of ..." or depend on "a module that defines the resource type 'archive'" (and what defines archive BTW, and how do you depend on that?).

To me `module_of` makes it possible to reference information that should have been available and part of the name/identifier in the first place. (This function would return names like 'camptocamp::archive', 'nanliu::archive')

When adding type reflection, I think the method in question is better named `has_attr` since `respond_to` is really asking about the type's behavior, not its structure. And if we start using reflection we probably want to be able to get all attributes, their names and types. An alternative implementation would be to implement `attributes(type)` which produces a hash of name => type mappings. It is then possible to check if that hash has a specific key, iterate over it etc. While more powerful it is still not something I recommend for reasons of maintainability - reflective code is best suited for conduits, error checking, logging, and other similar aspects. 

I do not want generic functions like these in stdlib as they would squat on behavior that I would like the puppet type system to have. I would prefer if they where implemented using the 4.x function API and name-spaced so they do not clash in the future. I also think such functions, if not designed to handle everything related to type reflection, they should be in a separate module, not in stdlib.

**Comment by danzilio** [comment]
@hlindberg you've articulated exactly what was in my head at the time I wrote this. There's definitely an inherent maintainability hit with this, but I think this is a rational design decision in many cases. Obviously, there are a number of ways to make this more maintainable. 

With the `module_of` implementation, the metadata would need to describe the types implemented in that module, as well as the classes inside the module (I think listing the classes inside the module would be very helpful in general). With this, we could implement type-based 'soft' dependencies (i.e. my module needs `example` class that implements `example` interface). 

```json
"dependencies": [
  { "class": "archive", "type_requirement": "somerequiredinterface" },
  { "name": "puppetlabs/stdlib", "version_requirement": ">=3.2.0 <5.0.0" }
]
```

I think 'soft' dependencies are desirable but, as of now, there's no way for a module to tell what implementation is available to it. If there was some `optional_dependency` object in `metadata.json` that listed prioritized optional dependencies (one must exist, if none exist, the first in the list is installed by `puppet module`). 

```json
"optional_dependencies": [
  { "name": "archive", "options": [
    { "name": "nanliu/archive", "version_requirement": ">=0.1.6 <0.2.2" },
    { "name": "camptocamp/archive", "version_requirement": ">=0.3.1 <0.5.2" }
  ]}
]
```

This would definitely make `puppet module` a more robust package management solution, but I'm not sure how many people are interested in this functionality.

I really like the idea of the `attributes(type)` implementation. I'm going to take a stab at it, but it sounds like this is something you'd rather keep out of stdlib. Until something like this is implemented in the type system, perhaps this would be a good candidate for extlib?

**Comment by igalic** [comment]
my thought was that when modules were name-spaced in puppet/environments, then we could "simply" fall-back on the dependencies from metadata.json

so, if puppetlabs/tomcat requires nanliu/archive, we could just use that.
now, lesaux/kibana4 can still depend on camptocamp/archive, and we can use both modules without too much headache.

of course, as @hlindberg says, this is "weak", and the question remains what to do with modules which don't even list dependencies, but just use them.

**Comment by hlindberg** [comment]
The new loader system bases visibility on the module dependencies; a module can only see what it has declared dependencies on. We have made modules that have no dependencies what so ever exempt from this rule (the see everything else). The intent is to deprecate the exemption and make this strict in a future version (i.e. the configuration gradually gets more reliable). In 4.0.0 (and 3.x with future parser), only the 4x function API makes use of the new loaders. The intent is to move the rest of the loaded entities over to the new loaders.

I am all for being able to describe everything in module metadata. Basically, it requires two things: modules declare what they require and what the provide. Each such element is a "capability" (borrowing a term from a system that works this way) that has a namespaced type, a name within that type, and a version range. The namespaced type follows the principles of "puppet" that is reserved for puppet core, and "puppet_x::author" is reserved per author. 

Flexibility is needed since it may not be possible to update all modules; i.e. I could know something about a module that I would like to make available as meta data and I want to re-export it (make it visible to others even if there was no declaration of this in the original module) - say that I invent an interface and want to describe that I know that X and Y comply with this interface. (OTOH, features like this makes it a lot more complex).

Most of this metadata can be derived from the content in a module when a module is built and this can take into account if something is private to the module (and then not publish it).

Naturally we only need a very simple scheme at the start, but I think it is a big mistake in nor providing mechanisms for proper name spacing - we are still only at the beginning of the evolution of the puppet echo-system (and see how much pain the lack of proper naming has caused to date).

wrt. to the function `attributes` (or whatever it ends up being), I can imagine that a set of well designed functions for type reflection end up in puppet core; this includes relection on types themselves and ability to get the type parameters (attributes being one such, the length of an array, the element type of an array examples of other attributes of types).

... ok, I am rambling...

**Comment by hlindberg** [comment]
why is this robot pinging this thread over and over again?

**Comment by nibalizer** [comment]
Sorry! Thats 'my' bot. We're gonna fix it to not spam but haven't done that yet. This is where we are tracking it: https://github.com/puppet-community/pcci/issues/4

**Comment by purpleidea** [comment]
On Wed, Jun 3, 2015 at 4:49 PM, Spencer Krum <notifications@github.com>
wrote:

> Sorry! Thats 'my' bot. We're gonna fix it to not spam but haven't done
> that yet. This is where we are tracking it: puppet-community/pcci#4
> <https://github.com/puppet-community/pcci/issues/4>
>


Pretty easy to stop the spamming by disabling it until your bot is fixed :)

**Comment by nibalizer** [comment]
It's been disabled.

**Comment by mhaskel** [comment]
Hi @danzilio , thanks for your work on this. This seems like it could be useful, but we don't want to include it in stdlib so I'd suggest publishing it as a separate module if you're still interested in this. Thanks again!

**Pull request closed without merging**
