### PR TITLE
added to_json function

### PR DESCRIPTION
**Pull request by KlavsKlavsen**
based on https://gist.github.com/halkeye/2287885

useful for example, if you want a hash into a config file.. (just as we have yaml() function - to output in yaml). For shell scripts its useful to output structured settings (hashes) as json - which can then be parsed with jq.

### CODE REVIEW

**Comment by tphoney** [comment]
Seems good, however this will definitely need tests and documented in the readme. 👍

**Comment by tphoney** [comment]
Hi @KlavsKlavsen , thanks for the work you have put into this pull request. However due to inactivity and not having appropriate documentation / needing rebased / not having appropriate tests added this pull request is being closed. If you want to re-submit this PR with the necessary changes, we will gladly look at the new pull request.

**Comment by KlavsKlavsen** [comment]
Thats absolutely fine. I'm sorry I can't squeeze the time out right now.. its on my (way too long) todo list :)

**Comment by tphoney** [comment]
Good luck with the list !

**Pull request closed without merging**
