### PR TITLE
MODULES-2457 - Remove newline from encoded string

### PR DESCRIPTION
**Pull request by mhaskel**

### CODE REVIEW

**Comment by nibalizer** [comment]
lgtm

**Comment by DavidS** [comment]
Would we be able to come up with an estimate how many people this change would trip over?

**Comment by mhaskel** [comment]
@DavidS hm, not sure. I just saw the MODULES ticket came in and that seemed reasonable / bug-like.

**Comment by DavidS** [comment]
Please consider #510 : adding the newlines is actually base64 conformant as the encoding specifies a maximum line length

**Comment by mhaskel** [comment]
Merged #510 instead, if the newline needs to be stripped it should be done with `chomp()`

**Pull request closed without merging**
