### PR TITLE
Fix load module metadata

### PR DESCRIPTION
**Pull request by cmurphy**
Fix spec test and add feature to allow absence of metadata.json.

### CODE REVIEW

**Comment by cmurphy** [comment]
ping @nibalizer

**Comment by DavidS** [comment]
Thanks for your contribution, Colleen!

**Comment by cmurphy** [comment]
Thanks @DavidS! When do you think this might get released? ;)

**Comment by nibalizer** [comment]
Nice!

**Comment by DavidS** [comment]
There is currently no release planned. Until there is one, you can use a reference to github in your Puppetfile to get this version. ;)

**Pull request merged**
