### PR TITLE
(MODULES-7181) Remove Stdlib::(Ipv4|IPv6|Ip_address)

### PR DESCRIPTION
**Pull request by baurmatt**
There was 3 different data types for ip validation before this commit.
This removes the Stdlib::(Ipv4|IPv6|Ip_address) data type in favour of
Stdlib::IP::* as those are way more complete.

### CODE REVIEW

**Comment by b4ldr** [comment]
as the one that introduced those types, i agree the we should only have one interface for this  [and the compat one].  The `Stdlib::IP::Address` types are much nicer then the ones i introduced so we should keep them

**Comment by pegasd** [comment]
The upcoming 5.0.0 release could be a good time to introduce these backwards-incompatible changes.

**Comment by pmcmaw** [comment]
@david22swan when merging can you ensure to squash and merge. There is a typo in my second commit. (Pressed enter and submitted by accident)

**Comment by HelenCampbell** [comment]
Thank you for the PR @baurmatt !

**Pull request merged**
