### PR TITLE
Add Stdlib::Mode type

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
I based my work off of the Unixpath type. Let me know if I'm missing anything.

**Comment by ripienaar** [comment]
`Mode` is perhaps a bit generic? `UnixFileMode` or similar be better? or just `FileMode` if you want to eventually support other OS?

**Comment by ghoneycutt** [comment]
Good idea, RI. I changed it to `Filemode`.

**Comment by ghoneycutt** [comment]
Thanks!

**Comment by ghoneycutt** [comment]
@david22swan could you please tag a new release with this functionality.

**Comment by david22swan** [comment]
Release is currently going out

**Pull request merged**
