### PR TITLE
Make get_module_path() work without environment

### PR DESCRIPTION
**Pull request by hasegeli**

### CODE REVIEW

**Comment by eputnam** [comment]
@hasegeli can you comment on the reasoning behind this change? possibly in the commit message :)

**Comment by HerrSpace** [comment]
Given a default.pp like.

``` puppet
node 'dev' {
    get_module_path('stdlib')
}
```

I get the following error when trying to use get_module_path with puppet apply:


```
vagrant@dev:/vagrant$ ls modules/
stdlib
vagrant@dev:/vagrant$ sudo puppet apply default.pp --modulepath=./modules --debug
Debug: Runtime environment: puppet_version=4.8.2, ruby_version=2.3.3, run_mode=user, default_encoding=UTF-8
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Loading external facts from /var/cache/puppet/facts.d
Info: Loading facts
Debug: Loading facts from /vagrant/modules/stdlib/lib/facter/puppet_settings.rb
Debug: Loading facts from /vagrant/modules/stdlib/lib/facter/facter_dot_d.rb
Debug: Loading facts from /vagrant/modules/stdlib/lib/facter/pe_version.rb
Debug: Loading facts from /vagrant/modules/stdlib/lib/facter/package_provider.rb
Debug: Loading facts from /vagrant/modules/stdlib/lib/facter/root_home.rb
Debug: Loading facts from /vagrant/modules/stdlib/lib/facter/service_provider.rb
Debug: Facter: Found no suitable resolves of 1 for ec2_metadata
Debug: Facter: value for ec2_metadata is still nil
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Failed to load library 'cfpropertylist' for feature 'cfpropertylist'
Debug: Failed to load library 'cfpropertylist' for feature 'cfpropertylist'
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Facter: value for agent_specified_environment is still nil
Debug: Facter: Found no suitable resolves of 1 for ec2_metadata
Debug: Facter: value for ec2_metadata is still nil
Debug: Facter: Found no suitable resolves of 1 for ec2_userdata
Debug: Facter: value for ec2_userdata is still nil
Debug: Facter: Found no suitable resolves of 1 for system32
Debug: Facter: value for system32 is still nil
Debug: Facter: Found no suitable resolves of 1 for dhcp_servers
Debug: Facter: value for dhcp_servers is still nil
Debug: Facter: value for is_rsc is still nil
Debug: Facter: value for is_rsc is still nil
Debug: Facter: Found no suitable resolves of 1 for rsc_region
Debug: Facter: value for rsc_region is still nil
Debug: Facter: value for is_rsc is still nil
Debug: Facter: Found no suitable resolves of 1 for rsc_instance_id
Debug: Facter: value for rsc_instance_id is still nil
Debug: Facter: value for cfkey is still nil
Debug: Facter: value for ipaddress6_eth0 is still nil
Debug: Facter: value for ipaddress6_eth1 is still nil
Debug: Facter: value for ipaddress6_lo is still nil
Debug: Facter: value for macaddress_lo is still nil
Debug: Facter: Found no suitable resolves of 1 for selinux_enforced
Debug: Facter: value for selinux_enforced is still nil
Debug: Facter: Found no suitable resolves of 1 for selinux_policyversion
Debug: Facter: value for selinux_policyversion is still nil
Debug: Facter: Found no suitable resolves of 1 for selinux_current_mode
Debug: Facter: value for selinux_current_mode is still nil
Debug: Facter: Found no suitable resolves of 1 for selinux_config_mode
Debug: Facter: value for selinux_config_mode is still nil
Debug: Facter: Found no suitable resolves of 1 for selinux_config_policy
Debug: Facter: value for selinux_config_policy is still nil
Debug: Facter: value for ipaddress6 is still nil
Debug: Facter: value for zfs_version is still nil
Debug: Facter: Found no suitable resolves of 1 for gce
Debug: Facter: value for gce is still nil
Debug: Facter: value for lsbrelease is still nil
Debug: Facter: Found no suitable resolves of 2 for swapencrypted
Debug: Facter: value for swapencrypted is still nil
Debug: Facter: Found no suitable resolves of 2 for iphostnumber
Debug: Facter: value for iphostnumber is still nil
Debug: Facter: Found no suitable resolves of 1 for processor
Debug: Facter: value for processor is still nil
Debug: Facter: value for sshdsakey is still nil
Debug: Facter: value for sshdsakey is still nil
Debug: Facter: value for sshfp_dsa is still nil
Debug: Facter: Found no suitable resolves of 1 for zonename
Debug: Facter: value for zonename is still nil
Debug: Facter: Found no suitable resolves of 1 for xendomains
Debug: Facter: value for xendomains is still nil
Debug: Facter: value for vlans is still nil
Debug: Facter: value for zpool_version is still nil
Debug: Facter: value for pe_version is still nil
Debug: Facter: value for pe_version is still nil
Debug: Facter: value for pe_version is still nil
Debug: Facter: Found no suitable resolves of 1 for pe_major_version
Debug: Facter: value for pe_major_version is still nil
Debug: Facter: value for pe_version is still nil
Debug: Facter: Found no suitable resolves of 1 for pe_minor_version
Debug: Facter: value for pe_minor_version is still nil
Debug: Facter: value for pe_version is still nil
Debug: Facter: Found no suitable resolves of 1 for pe_patch_version
Debug: Facter: value for pe_patch_version is still nil
Debug: Puppet::Type::Package::ProviderRpm: file rpm does not exist
Debug: Puppet::Type::Package::ProviderAptrpm: file rpm does not exist
Debug: Puppet::Type::Package::ProviderFink: file /sw/bin/fink does not exist
Debug: Puppet::Type::Package::ProviderPkgng: file /usr/local/sbin/pkg does not exist
Debug: Puppet::Type::Package::ProviderAix: file /usr/bin/lslpp does not exist
Debug: Puppet::Type::Package::ProviderAptitude: file /usr/bin/aptitude does not exist
Debug: Puppet::Type::Package::ProviderSun: file /usr/bin/pkginfo does not exist
Debug: Puppet::Type::Package::ProviderUrpmi: file urpmi does not exist
Debug: Puppet::Type::Package::ProviderPacman: file /usr/bin/pacman does not exist
Debug: Puppet::Type::Package::ProviderYum: file yum does not exist
Debug: Puppet::Type::Package::ProviderDnf: file dnf does not exist
Debug: Puppet::Type::Package::ProviderSunfreeware: file pkg-get does not exist
Debug: Puppet::Type::Package::ProviderOpenbsd: file pkg_info does not exist
Debug: Puppet::Type::Package::ProviderFreebsd: file /usr/sbin/pkg_info does not exist
Debug: Puppet::Type::Package::ProviderPkg: file /usr/bin/pkg does not exist
Debug: Puppet::Type::Package::ProviderNim: file /usr/sbin/nimclient does not exist
Debug: Puppet::Type::Package::ProviderRug: file /usr/bin/rug does not exist
Debug: Puppet::Type::Package::ProviderOpkg: file opkg does not exist
Debug: Puppet::Type::Package::ProviderPuppet_gem: file /opt/puppetlabs/puppet/bin/gem does not exist
Debug: Puppet::Type::Package::ProviderZypper: file /usr/bin/zypper does not exist
Debug: Puppet::Type::Package::ProviderUp2date: file /usr/sbin/up2date-nox does not exist
Debug: Puppet::Type::Package::ProviderPortupgrade: file /usr/local/sbin/portupgrade does not exist
Debug: Puppet::Type::Package::ProviderPkgin: file pkgin does not exist
Debug: Puppet::Type::Package::ProviderPortage: file /usr/bin/emerge does not exist
Debug: Puppet::Type::Package::ProviderTdnf: file tdnf does not exist
Debug: Puppet::Type::Package::ProviderHpux: file /usr/sbin/swinstall does not exist
Debug: Puppet::Type::Package::ProviderPorts: file /usr/local/sbin/portupgrade does not exist
Debug: /Package[dummy]: Provider apt does not support features virtual_packages; not managing attribute allow_virtual
Debug: Puppet::Type::Service::ProviderInit: false value when expecting true
Debug: Puppet::Type::Service::ProviderOpenbsd: file /usr/sbin/rcctl does not exist
Debug: Puppet::Type::Service::ProviderGentoo: file /sbin/rc-update does not exist
Debug: Puppet::Type::Service::ProviderDaemontools: file /usr/bin/svc does not exist
Debug: Puppet::Type::Service::ProviderLaunchd: file /bin/launchctl does not exist
Debug: Puppet::Type::Service::ProviderRunit: file /usr/bin/sv does not exist
Debug: Puppet::Type::Service::ProviderOpenrc: file /bin/rc-status does not exist
Debug: Puppet::Type::Service::ProviderRedhat: file /sbin/chkconfig does not exist
Debug: Puppet::Type::Service::ProviderUpstart: 0 confines (of 4) were true
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Error: Evaluation Error: Error while evaluating a Function Call, Could not find module stdlib in environment production at /vagrant/default.pp:2:5 on node dev
```

**Comment by HerrSpace** [comment]
@eputnam So this is rather a bugfix then a feature 👍

**Comment by eputnam** [comment]
Thanks @HerrSpace! Interesting. Looks like tests definitely need to be updated.

**Comment by hlindberg** [comment]
The function `module_directory(module_name)` in puppet (since Puppet 5.5.0) returns the path to the directory that is the root of the given module's name.
That implementation is also the right way of finding a module in an environment. Suggest doing the same as this function to give users of older puppet versions the same functionality. Also, please update the docs to say that from Puppet 5.5.0 there is `module_directory` in puppet.

**Comment by hlindberg** [comment]
#922 adds mention of `module_directory` function so no need to do that.

**Comment by david22swan** [comment]
@hasegeli I'm sorry to bother you but I was wondering if there was any movement on this PR?

**Comment by hasegeli** [comment]
There isn't.  You may pick it up and fix or close it.  I am not doing Puppet anymore.

**Comment by david22swan** [comment]
@hasegeli I'm sorry to hear that but I wish you luck in any of your future endeavors.
Best Wishes

**Pull request closed without merging**
