### PR TITLE
(MODULES-3980) Fix ipv4 regex validator

### PR DESCRIPTION
**Pull request by ntpttr**
The current pattern for stdlib::compat::ipv4 is incorrect, and
will return true for any four numbers separated with periods.
This commit improves the regex to validate that the IP octets
are between 1 and 255.

### CODE REVIEW

**Comment by ntpttr** [comment]
Looks like jobs with ruby < 2.0 are failing because of a dependency with parallel_tests

**Comment by hunner** [comment]
Also see #660

**Comment by hunner** [comment]
We are working on the parallel_tests fix via modulesync_config, so please don't edit the Gemfile directly (see https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/Gemfile#L1 )

**Comment by hunner** [comment]
Oh, I see you already did the modulesync :D

**Pull request closed without merging**
