### PR TITLE
Update to puppet-module-gems 1.0, pdk-templates and new rubocop

### PR DESCRIPTION
**Pull request by DavidS**

### CODE REVIEW

**Comment by tphoney** [comment]
@DavidS i am sure you are aware that moving the the new style of hashes it will break older versions of puppet. Are you happy that the next release of Stdlib will be a major release. 
I am happy with this

**Review by sanfrancrisko — APPROVED** [review]

**Comment by pmcmaw** [comment]
Thank you for this PR @DavidS :-)

**Review by pmcmaw — CHANGES_REQUESTED** [review]
In line with @tphoney comments above:
We plan to merge this after EOL of Puppet5 and release of Puppet7.
So this will be in approx a month or so. 

'Requesting changes' for no reason other than to safeguard and avoid merge.

**Comment by pmcmaw** [comment]
Closing as #1165 was merged. 
It includes these changes, a rebase and a few additional rubocop fixes.

**Pull request closed without merging**
