### PR TITLE
(stdlib) Minor edit

### PR DESCRIPTION
**Pull request by clairecadman**
This commit updated to wording to match the README.

### CODE REVIEW

**Comment by pmcmaw** [comment]
@hlindberg you happy with these changes?

**Comment by hlindberg** [comment]
It is fine, but maybe wait until big PR is merged as it is easier to rebase this on top of that if there is a conflict.

**Comment by pmcmaw** [comment]
@clairecadman would you mind rebasing please? 👍

**Comment by hlindberg** [comment]
I tried to use the github UI for this, but it did a merge instead of a rebase :-(
It is a single comma in the PR, will fix this directly instead - would otherwise have to take over the branch and rebase it and do a new PR - too much work for very small change.

**Comment by hlindberg** [comment]
Change pushed to master. Closing this PR.

**Pull request closed without merging**
