### PR TITLE
5.0.0 - Release Prep

### PR DESCRIPTION
**Pull request by david22swan**

### CODE REVIEW

**Comment by david22swan** [comment]
@clairecadman Could you take a look at the summary for this changelog and tell me what you think??

**Comment by pmcmaw** [comment]
@david22swan  You will want this against release.

**Comment by david22swan** [comment]
Changes made

**Comment by pmcmaw** [comment]
I have updated your PR title, can you update the summary to be like the following:
'This is a major release which removes support for Scientific 5 and Debian 7. This also contains a lot of work around updating functions that have now been migrated into Puppet itself. This release will be used as a pinning point as there are plans to remove support for all puppet versions less than 4 in the next release.'

**Comment by david22swan** [comment]
updated

**Pull request merged**
