### PR TITLE
Add is_ipv4_address and is_ipv6_address functions

### PR DESCRIPTION
**Pull request by gfidente**
These are useful when making decisions based on the type of IP
address received.

### CODE REVIEW

**Comment by EmilienM** [comment]
Why not re-using validate_ipv6_address and add an option to not fail the catalog but just return False?
That would reduce the code impact and could be backward compatible if you set the failure to True by default.

**Comment by HelenCampbell** [comment]
Hey @gfidente , thank you for your work! This would be a welcome addition to stdlib. Would you be willing to make the changes suggested by @EmilienM ? I can merge in as-is, however the changes suggested would make for a good improvement.

**Comment by hunner** [comment]
The `validate_*` messages traditionally fail the compile if they are unmatched so creators don't have to hand-write the logic and failure messages over and over, and `is_*` return true/false for actionable items.

This would be improved by updating the validate ipv4/6 functions to call the is_* methods and raise a failure on false return, but not required.

**Comment by hunner** [comment]
Perhaps a `is_ip_address` would be useful too...

**Comment by gfidente** [comment]
hi all, thanks for checking this!

maybe we can add a parameter for IPv6 to is_ip_address and call the same code from all is_ipv4 is_ipv4 and validate_* ?

**Pull request merged**
