### PR TITLE
Add globbing for loadyaml

### PR DESCRIPTION
**Pull request by sspreitzer**
Can someone please review and guide/help me with the rspec?

### CODE REVIEW

**Comment by DavidS** [comment]
Hi Sasha,

thanks for your contribution. The tests complain about the function being changed from returning the data in the file to returning the filename(s) in an array, which matches your code changes, which in turn is not what I assume you're intending to.

To address this, first you need to decide how multiple yaml files should be merged, and then add that to the implementation. The existing tests need to continue to pass as is to avoid breaking existing code.

**Comment by sspreitzer** [comment]
Hi DavidS

Thank you for the hint, will follow up on that later!

**Comment by sspreitzer** [comment]
Hi David

I think some of the errors should be fixed now. For the others a change to rspec might be needed as they function design also changes.
* It is now possible to provide a list of paths to be globbed
* The globbing mechanism can not check whether a file is available or not as it will return all available files. If they are not available, they will not be parsed

**Comment by DavidS** [comment]
Looking at https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/spec/functions/loadyaml_spec.rb , you'll need to modify the tests at L10 and L19 to match the implementation, e.g. to `Dir.expects(:glob). ...`

The test expecting multiple arguments to throw an error can go away, since the new function can cope with multiple arguments now.

Since you're expanding the functionality, you should also add test cases to cover this:

* What happens if you pass in a glob that matches multiple files?
* What happens if one of the files contains non-Hash data?
* What happens if there is a directory matching the glob?

**Comment by sspreitzer** [comment]
Hi @DavidS 

Thank you for your help! :-)

> What happens if one of the files contains non-Hash data?

This is an interesting question. Is there a design pattern that tells whether Puppet should Error or can it silently proceed with skipping the wrong file in such case?
Both ways are implementable.

**Comment by DavidS** [comment]
Currently the loadyaml function supports arbitrary data in the file,
including arrays, hashes, strings and numbers. Dropping some data might be
very surprising. What would you think about e.g. putting the result of each
file into an array cell? with the new puppet 4 language features, people
can munge the data as they need themselves.
Thinking about that I had another question: how can you avoid globbing, if
you do not want this behavior, e.g. in security-critical scenarios, or when
your file name just has a asterisk or a question mark in it? Together with
the question above, it might be much easier to implement a separate glob()
function, that just expands the filenames and allow people to use that as
an input to the unmodified loadyaml function. Using puppet 4 language would
make that quite possible and glob() can be used with every function that
requires a filename (like generate() or template()).

**Comment by sspreitzer** [comment]
PS.: I am still working on this..

**Comment by HelenCampbell** [comment]
Hey @sspreitzer , thank you for your contribution! Just following up on this as it's been a while now since this PR has been active. Is there anything we can help you with further? Our usual policy is to close inactive PRs after 30 days or so, but I don't want to close this incase you are still actively working on it.

**Comment by sspreitzer** [comment]
hi helen
absolutely, i will follow up on this this weekend. sry for the delay. got million other things running

**Comment by sspreitzer** [comment]
okay, forget about this PR, I will create a seperate glob function and later on patch loadyaml to support its inpute. thanks a lot.

**Comment by HelenCampbell** [comment]
@sspreitzer Thanks for the update on this, feel free to give @DavidS or I a ping whenever you need any help or review on your new PR. Again, thank you for all the effort :)

**Pull request closed without merging**
