### PR TITLE
(MODULES-5680) Added new function sprintf_hash to allow using named references

### PR DESCRIPTION
**Pull request by vStone**
See docs, tests

### CODE REVIEW

**Comment by vStone** [comment]
Not sure why windows doesn't like this... :/

**Comment by david22swan** [comment]
Test's failed a second time when rekicked. Unable to merge at this time

**Comment by david22swan** [comment]
All failures seem to originate from line 22 of lib/puppet/functions/sprintf_hash.rb

**Comment by david22swan** [comment]
@vStone 
Any movement on this??
Be warned that I'm moving to do a clean release so anything that isn't merged will be closed.

**Comment by vStone** [comment]
Although the documentation suggests `return_type` should be usable from puppet 4.7, looks like its not quite the case.

**Pull request merged**
