### PR TITLE
Add new function `deep_merge`.

### PR DESCRIPTION
**Pull request by riton**
* Add rspec code to test new functionnality (didn't test the raise of an error if no _deep_merge_ module is available)
* Add documentation to README
* Add example in tests/deep_merge.pp

### CODE REVIEW

**Comment by cyberious** [comment]
@riton I am not a fan of requiring a gem to be installed in order for the functionality to work, especially as in a masterless scenario this will fail over on Windows, I understand the use case and reasons but not the implementation to fail hard when the gem is unable to be loaded

**Comment by DavidS** [comment]
1) this needs rebasing against a current version of stdlib.
2) given the massive change in behavior, it would be much better if this were a separate function, so people can make their own decisions/tradeoffs. I would suggest `deep_merge_gem` or similar.
3) a new function can significantly reduce complexity and test effort by just passing through all arguments to the gem and just checking for the right function to be called.

**Comment by mhaskel** [comment]
@riton ping?

**Comment by riton** [comment]
Here I'm guys, sorry for the delay !

**Comment by riton** [comment]
So I'm a little confused here.
@cyberious said that having a dependency on an external _gem_ wasn't a good thing.
I understood that you wasn't interested in this _pull request_ anymore.

And 2 weeks ago, @DavidS seems to say that this needs work, but seems a good idea after all.

Are you still interested in this function ?

**Comment by DavidS** [comment]
@riton both issues need to be addressed before the functionality can be merged. I pointed out a way to do so: create a new function, thereby not breaking backwards compatibility, and creating a place where it can be described in detail what needs to be done to use this function.

**Comment by DavidS** [comment]
In the "worst" case, this might be a candidate for https://github.com/puppet-community/puppet-extlib

**Comment by nibalizer** [comment]
We welcome speculative functions into extlib so that they can be collected and perused and used. We've not had any functions promote out of extlib into stdlib, but that would be a huge success I think.

**Comment by igalic** [comment]
:+1:

**Comment by cyberious** [comment]
@riton I am not a fan of gem dependencies but if it is called out explicitly from the function name at least it is a little more clear that this gem MUST be installed.

**Comment by bmjen** [comment]
Thanks for the contribution @riton. I think the consensus here is that this function would fit best in https://github.com/puppet-community/puppet-extlib

**Pull request closed without merging**
