### PR TITLE
(MODULES-9049) Add type alias for 'yes' and 'no'.

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
https://tickets.puppetlabs.com/projects/MODULES/issues/MODULES-9049

**Comment by ghoneycutt** [comment]
Could someone please take a look, thank you!

**Comment by hlindberg** [comment]
I think this is fine - it would be nice to make them case independent which could be done by using a `Pattern` data type with a regexp where the case independent flag is turned on.
For example:
```
type YesNo = Pattern[/\A(?i:(yes|no))\z/]
```
This works hand in hand with `Boolean($val)` since it turns a `yes/no` into boolean in the same case independent way.

**Comment by ghoneycutt** [comment]
Good idea Henrik. I'll get the PR amended.

**Comment by ghoneycutt** [comment]
@hlindberg look good?

**Comment by tphoney** [comment]
Looks good to me, Merging. 

Thanks for the PR @ghoneycutt

**Pull request merged**
