### PR TITLE
URI.escape for the array case was incorrect.

### PR DESCRIPTION
**Pull request by kainz**
The previous commit to uriescape() changed the implementation to use the ruby default escape list for URI.escape(), but did not change the call triggered when uriescape() was called on an array, triggering ruby errors.

### CODE REVIEW

**Comment by cyberious** [comment]
@kainz can you please check and add the unit tests

**Comment by kainz** [comment]
For a 'sufficiently' long definition of weekend, here you go :)

**Comment by igalic** [comment]
@kainz couple of general comments:

you might wanna redo this whole pr, using the [github flow](https://guides.github.com/introduction/flow/index.html) work-flow, this should make things like [rebase](http://git-scm.com/book/en/Git-Branching-Rebasing) and [squashing](http://www.git-scm.com/book/en/Git-Tools-Rewriting-History#Squashing-Commits).

you can also [add all your email addresses](https://help.github.com/articles/setting-your-email-in-git/), then your commits will be associated with your account (if that's important to you;).

**Comment by kainz** [comment]
@igalic TBH i don't really feel a need to rebase, and this is basically orphan code for me now.  Merge or close at your leisure. :)

**Comment by mhaskel** [comment]
@kainz thanks for the contribution. I rebased and merged manually.

**Pull request closed without merging**
