### PR TITLE
Rubocop Implementation

### PR DESCRIPTION
**Pull request by david22swan**
A commit for the purpose of tracking changes

### CODE REVIEW

**Comment by david22swan** [comment]
As a note, I have divided the ruby_spec.rb into three as I found it to unwieldy to use.

**Comment by david22swan** [comment]
Finished and Waiting on lean release

**Comment by david22swan** [comment]
Ready for merge

**Comment by pmcmaw** [comment]
LGTM. Another +1 and I will get it merged 👍

**Comment by sean797** [comment]
Looks like this broken our use of `min()` :( I'm not sure how to fix it?

https://travis-ci.org/theforeman/puppet-pulp/jobs/305347085
https://github.com/theforeman/puppet-pulp/blob/master/manifests/params.pp#L113

**Comment by david22swan** [comment]
A fix has been merged in. 
https://github.com/puppetlabs/puppetlabs-stdlib/pull/850
Apologies for any inconvenience

**Comment by pmcmaw** [comment]
@sean797 I have created the following PR which should resolve your issue. Just waiting on it going through CI and I will get it merged as soon as possible. If this does not resolve your issue please let me know as soon as possible. 

:-)

https://github.com/puppetlabs/puppetlabs-stdlib/pull/850

**Comment by matejzero** [comment]
I just found out, this broke stdlib on CentOS 6 with puppet 3.8. 

I opened a ticket on JIRA: https://tickets.puppetlabs.com/browse/MODULES-6107

Problem is the hash syntax, which is not supported by ruby 1.8, which is the default on CentOS 6.

**Comment by razorsedge** [comment]
Puppet 2.7.26 and 3.x with Ruby 1.8.7 is still broken.
https://travis-ci.org/razorsedge/puppet-snmp/builds/326051819
```
  155) snmp::snmpv3_user on a supported osfamily, Suse with snmptrapd settings should contain Exec[create-snmpv3-user-myTRAPuser] with before => "Service[snmptrapd]", command => "service snmptrapd stop ; sleep 5 ; echo \"createUser myTRAPuser SHA \\\"myauthpass\\\"\" >>/var/lib/net-snmp/snmptrapd.conf && touch /var/lib/net-snmp/myTRAPuser-snmptrapd", require => ["Package[snmpd]", "File[var-net-snmp]"] and creates => "/var/lib/net-snmp/myTRAPuser-snmptrapd"
     Failure/Error: )}
     Puppet::Error:
       Could not autoload puppet/parser/functions/validate_numeric: /home/travis/build/razorsedge/puppet-snmp/spec/fixtures/modules/stdlib/lib/puppet/parser/functions/validate_numeric.rb:62: syntax error, unexpected '>'
           validator = ->(num) do
                         ^
       /home/travis/build/razorsedge/puppet-snmp/spec/fixtures/modules/stdlib/lib/puppet/parser/functions/validate_numeric.rb:62: syntax error, unexpected kDO, expecting kEND
       /home/travis/build/razorsedge/puppet-snmp/spec/fixtures/modules/stdlib/lib/puppet/parser/functions/validate_numeric.rb:99: syntax error, unexpected kEND, expecting $end on node travis-job-razorsedge-puppet-snmp-326051820.travisci.net
     # ./spec/defines/snmp_snmpv3_user_spec.rb:251
```

**Comment by matejzero** [comment]
Looking at the [diff](https://github.com/puppetlabs/puppetlabs-stdlib/compare/7999ff2aebbd2d85a231318f1e466b36d6dab84e...puppetlabs:21e7ce8fc3cdacab50b71d1973d7c80ed0543fd3?diff=unified&name=21e7ce8fc3cdacab50b71d1973d7c80ed0543fd3) between broken version (which dropped support for Ruby 1.8) and latest commit in those files, there seem to be little changes (only 2). 

I think you are right!

This is the [diff](https://github.com/puppetlabs/puppetlabs-stdlib/commit/7999ff2aebbd2d85a231318f1e466b36d6dab84e#diff-3a4d0dc464872da05240fa18d77517f5) for Rubocop implementation, that dropped Ruby 1.8 support.

And this is the [rollback diff](https://github.com/puppetlabs/puppetlabs-stdlib/compare/7999ff2aebbd2d85a231318f1e466b36d6dab84e...puppetlabs:21e7ce8fc3cdacab50b71d1973d7c80ed0543fd3?diff=unified&name=21e7ce8fc3cdacab50b71d1973d7c80ed0543fd3). There seem to a be a lot of thinks missing.

Strangely I'm not hitting those issues for some reason, although I'm also using validate_integer/array/hash/book (not numeric though).

**Comment by natebc** [comment]
Confirmed that the Rubocop implementation lead some changes that didn't get rolled back.
Relevant bits are:
RHEL 6.9 puppet servers with:

puppet-3.8.7-1.el6.noarch
ruby-1.8.7.374-5.el6.x86_64
using puppetlab-stdlib-4.25.1

We hit the same error as @razorsedge 
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/parser/functions/validate_integer: /etc/puppet/environments/development/modules/stdlib/lib/puppet/parser/functions/validate_integer.rb:100: syntax error, unexpected '>'
    validator = ->(num) do
                  ^
/etc/puppet/environments/development/modules/stdlib/lib/puppet/parser/functions/validate_integer.rb:100: syntax error, unexpected kDO, expecting kEND
/etc/puppet/environments/development/modules/stdlib/lib/puppet/parser/functions/validate_integer.rb:137: syntax error, unexpected kEND, expecting $end on node 
```

**Comment by jsjohnst** [comment]
FYI, this is still an issue... Are we just cutting support for RHEL<7 and Puppet 3.x?

**Pull request merged**
