### PR TITLE
Add validate_domain_name function

### PR DESCRIPTION
**Pull request by frapex**
Add validate_domain_name function.

### CODE REVIEW

**Comment by frapex** [comment]
The two travis-ci checks fail because of an error in examples/file_line.pp, which is not part of this commit. Can someone take a look?

**Comment by tphoney** [comment]
I am struggling to see how this is different to https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/lib/puppet/parser/functions/is_domain_name.rb can you explain ?

**Comment by frapex** [comment]
For almost every is_<something> function there is also a validate_<something> function (is_absolute_path and validate_absolute_path, is_email_address and validate_ip_address, et cetera)

There is no validate function available for the is_domain_name function. This commit adds the missing validate_domain_name function.

**Comment by frapex** [comment]
@tphoney can you please look at this pull request and merge it? It has been almost four months since the pull request was first created and almost three weeks since I added additional info and rebased.

**Comment by tphoney** [comment]
Thanks for this @frapex apologies for the delay, i was stuck on other things.

**Comment by frapex** [comment]
@tphoney thanks!

**Pull request merged**
