### PR TITLE
Add a round function to complement ceiling and floor

### PR DESCRIPTION
**Pull request by npwalker**

### CODE REVIEW

**Comment by tphoney** [comment]
@npwalker apologies can you rebase this, if not i will look at it next week.

**Comment by npwalker** [comment]
@tphoney rebased.

**Comment by eputnam** [comment]
just kidding, needs another rebase @npwalker .

**Comment by eputnam** [comment]
thanks @npwalker !

**Comment by tphoney** [comment]
yup !, apologies for the delay / rebasing

Great work @npwalker

**Pull request merged**
