### PR TITLE
Add localhost to defined Type Stdlib::Host

### PR DESCRIPTION
**Pull request by cocker-cc**

### CODE REVIEW

**Comment by alexjfisher** [comment]
Is this actually needed?  I think `Stdlib::Fqdn` will already allow `localhost`.

**Comment by cocker-cc** [comment]
`Stdlib::Fqdn` does not accept `localhost`, as there is no dot in `localhost`.

**Comment by alexjfisher** [comment]
There's no dot in `example`, but according to the tests, that is a valid `Stdlib::Fqdn`
https://github.com/puppetlabs/puppetlabs-stdlib/blob/3310305e2cecb44e986c95706f512099829ec733/spec/type_aliases/fqdn_spec.rb#L6

**Comment by cocker-cc** [comment]
Ayea, indeed You're right.  I must have overseen something…  Sorry for the noise.  I'll close this one.

**Pull request closed without merging**
