### PR TITLE
Added netmask2cidr function

### PR DESCRIPTION
**Pull request by hkumarmk**
This function help to convert network mask to cidr notation.

### CODE REVIEW

**Comment by tphoney** [comment]
ping @hkumarmk Could you please rebase this. A few more tests would also be good.

**Comment by elyscape** [comment]
It might also be a good idea to validate that it's a valid network mask, maybe by doing something like this:
```ruby
mask = IPAddr.new(args[0]).to_i.to_s(2)
is_valid = mask.match(/\A1*0*\z/)
raise Puppet::ParseError, "Invalid mask: #{args[0]}" unless is_valid
mask.count("1")
```

**Comment by elyscape** [comment]
Also, `require` is not something that requires `end`.

**Comment by mhaskel** [comment]
Hi @hkumarmk, thanks for the contribution. We haven't heard from you in a while, so I'm going to close this PR for now. If this is still something you're interested in having added to the module, please address the comments, above, and also update the README with documentation on the new function and resubmit. Thanks again!

**Pull request closed without merging**
